### ISSUE TITLE
2 line captions on images

### ISSUE THREAD

**Issue by monahakk** [BCLibraries/burns-exhibits#11]
**Is your feature request related to a problem? Please describe.**
We'd like to have two-lines of captions for images in each of the templates (similar to how gallery works now), where the first line is the bolded headline. If possible, we'd like the second line to be a smaller font.  That will enable us to have a descriptive caption for each image, followed by the citation information for the image. 

See http://http://localhost:1313/eva-mckee-irish_artisan/ for examples of the types of captions we want to use (and how they currently look clunky on the introduction page and the biography page)

**Describe alternatives you've considered**
Let us know if this is impossible and we'll figure out a different captioning method.

**Comment by Otterfan** [comment]
I've added a `description` attribute to `{% figure %}` and `{% lagefigure %}` that will add the second line below the `headline`, e.g.:

```
{{% figure src="../intro-image.jpg" headline="Consectetur Ligula Venenatis Vestibulum" side="left" %}}
```

or 

```
{{% largefigure src="../intro-image.jpg" headline="Venenatis Euismod Tristique" description= "Second line here" size="medium" %}}
Curabitur blandit tempus porttitor. Donec id elit non mi porta gravida at eget metus. Curabitur blandit tempus porttitor. Aenean lacinia bibendum nulla sed consectetur.
{{% /largefigure %}}
```
