### ISSUE TITLE
Center align on large figures

### ISSUE THREAD

**Issue by monahakk** [BCLibraries/burns-exhibits#31]
**Describe the bug**
For landscape images, align="center" attribute on large figures is still not placing them in the center of the page. Or, at least, they don't look centered compared to the other items on the page?

**Link to example**
http://localhost:1313/being-social/crowd-funding/
Check the Irish National League Anti-Coercion Fund certificate and the Lawn Party Fundraiser 1908

**Additional context**
Telling me I'm just seeing things and they really are centered is an acceptable solve to this bug too. It may be fine??

**Comment by Otterfan** [comment]
I've patched up the centering on large figures. I think we might also need to make one-item gallery rows center correctly. I'll add that to the list for later.
