### ISSUE TITLE
Page not loading?

### ISSUE THREAD

**Issue by monahakk** [BCLibraries/burns-exhibits#39]
**Describe the bug**
One page in Pray for Us (prayer-cards-through-the-ages) has an extremely slow load time. Is this a short-term development thing, or a real issue? Can we do something so that isn't true in production?

**Link to example**
http://localhost:1313/pray-for-us/prayer-cards-through-the-ages/

**To Reproduce**
I can't load it on Firefox 60.8.0 and Shelley can't load it in Chrome. Both running Windows.

**Comment by Otterfan** [comment]
I optimized the images in this exhibit (066dc86f353b6b39a6a49578553ea57654555ee4), which should speed things up enough to make the page usable.

The lightbox is loading both the big and thumbmail versions of every image when the page loads, which is slowing things down. If I have time this afternoon, I'll change that to load just thumbnail on page load and load the big image when it's clicked.
