### ISSUE TITLE
Headline in large-image-gallery

### ISSUE THREAD

**Issue by monahakk** [BCLibraries/burns-exhibits#9]
**Describe the bug**
The large-image-gallery template has a space for headlines for each image, but they aren't showing up on the page.

**Link to example**
http://localhost1313/harp-traditions-of-ireland/early-harps

**To Reproduce**
1. Go to 'http://localhost1313/harp-traditions-of-ireland/early-harps.'
2. See that there are no headlines under the image
3. Check the source file and confirm that Kathleen isn't crazy, and that they should be there

**Expected behavior**
Each image should have a headline under it

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version: 60.6.1esr

**Additional context**
This may have been the original issue I found with the Eva McKee exhibit ticket that we couldn't remember the details of?

**Comment by Otterfan** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/210404/56918235-79ebb680-6a8b-11e9-9894-cfc4b1c4f8c1.png)
